import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, ChevronLeft } from "lucide-react";

type Language = "en" | "th";

export const copy = {
  en: {
    back: "Back to INTEVIA", nav: "RFID / IoT Solutions", contact: "Start a conversation",
    heroLabel: "RFID · IOT · INDUSTRIAL SYSTEMS", heroTitle: ["Connect the", "physical world", "to better decisions"], heroText: "INTEVIA helps international organisations design, validate and improve the systems that connect products, people and production in Thailand.", heroAction: "Explore our capabilities",
    introLabel: "OUR RFID & INDUSTRIAL CAPABILITIES", introTitle: ["From plant design", "to yield up"], introText: "A practical engineering and operations partner for businesses with supplier and factory networks in Thailand. We bring visibility to the floor, discipline to the study and action to the improvement plan.",
    services: [
      ["01", "PLANT DESIGN", "Design the flow before you build it", "Plan layouts, material flow, workstations and production interfaces for safer, clearer and more productive operations."],
      ["02", "WORK STUDY", "Make every motion count", "Observe work as it happens, identify waste and establish a fact-based standard for cycle time, capacity and manpower."],
      ["03", "PRODUCT CAPABILITY", "Know what the process can deliver", "Translate product requirements into measurable process capability, control plans and supplier readiness."],
      ["04", "YIELD UP", "Turn loss into output", "Find the root causes behind scrap, rework and variation, then build the improvement loop that lifts yield sustainably."],
    ],
    rfidLabel: "RFID / NFC / IOT SOLUTIONS", rfidTitle: ["Make every item", "visible"], rfidText: "We prepare the hardware, application logic and integration layer required to deploy RFID and IoT use cases with confidence—from the first tag read to a connected operating system.",
    stack: [["01", "TAG", "Unique identity and product data"], ["02", "READER", "Reliable signal capture"], ["03", "ANTENNA", "The communication bridge"], ["04", "SOFTWARE", "Data, workflow and integration"]],
    techLabel: "CORE TECHNOLOGY", techTitle: "The right frequency for the right decision", tech: [["LF", "125–134 kHz", "Close-range identification", "Animal identification · Access control"], ["HF / NFC", "13.56 MHz", "Tap-and-connect experiences", "Smart cards · Payments · Authenticity"], ["UHF", "860–960 MHz", "Long-range inventory visibility", "Logistics · Production · Asset tracking"]],
    projectsLabel: "WHERE IT CREATES VALUE", projectsTitle: ["Connect the data", "to the work"], projects: [["PRODUCT TRACEABILITY", "Follow a product from production through distribution with live status and history."], ["INVENTORY CONTROL", "Locate, count and move stock with less manual work and less uncertainty."], ["SUPPLIER QUEUE", "Coordinate suppliers, schedules and receiving with one operational view."], ["AUTHENTICITY & NFC", "Give products a verifiable identity and customers a trusted interaction."], ["PRODUCTION VISIBILITY", "Make the check sheet, approval step and dashboard part of one flow."], ["CONNECTED DEVICES", "Extend the system into dispensing, access, patient or event experiences."]],
    ctaLabel: "READY TO CONNECT THE DOTS?", ctaTitle: ["Start with the", "operational question"], ctaText: "Tell us where visibility, capacity or quality is getting in the way. We will help frame the next practical move.", ctaAction: "Talk to INTEVIA", footer: "RFID and industrial systems for organisations ready to move with intent."
  },
  th: {
    back: "กลับสู่ INTEVIA", nav: "RFID / IoT Solutions", contact: "เริ่มต้นพูดคุย",
    heroLabel: "RFID · IOT · INDUSTRIAL SYSTEMS", heroTitle: ["เชื่อมโลกจริง", "เข้ากับข้อมูล", "เพื่อการตัดสินใจที่ดีขึ้น"], heroText: "INTEVIA ช่วยองค์กรต่างชาติออกแบบ ตรวจสอบ และยกระดับระบบที่เชื่อมสินค้า ผู้คน และกระบวนการผลิตในประเทศไทย", heroAction: "ดูความสามารถของเรา",
    introLabel: "ความสามารถด้าน RFID และอุตสาหกรรม", introTitle: ["ตั้งแต่การออกแบบโรงงาน", "สู่การเพิ่ม Yield"], introText: "partner ด้านวิศวกรรมและการดำเนินงานสำหรับธุรกิจที่มี supplier และโรงงานในประเทศไทย เราสร้าง visibility ให้หน้างาน วางระเบียบให้การศึกษา และเปลี่ยนแผนปรับปรุงให้เกิดผลจริง",
    services: [
      ["01", "PLANT DESIGN", "ออกแบบ flow ให้ชัดก่อนเริ่มสร้าง", "วาง layout, material flow, workstation และ interface ของการผลิต เพื่อให้การดำเนินงานปลอดภัย ชัดเจน และมีประสิทธิภาพขึ้น"],
      ["02", "WORK STUDY", "ทำให้ทุก movement สร้างคุณค่า", "สังเกตการทำงานจริง ค้นหา waste และสร้างมาตรฐานจากข้อมูลด้าน cycle time, capacity และ manpower"],
      ["03", "PRODUCT CAPABILITY", "รู้ว่ากระบวนการส่งมอบอะไรได้บ้าง", "แปลง product requirement ให้เป็น process capability, control plan และความพร้อมของ supplier ที่วัดผลได้"],
      ["04", "YIELD UP", "เปลี่ยน loss ให้เป็น output", "ค้นหา root cause ของ scrap, rework และ variation แล้วสร้าง improvement loop เพื่อเพิ่ม yield อย่างยั่งยืน"],
    ],
    rfidLabel: "RFID / NFC / IOT SOLUTIONS", rfidTitle: ["ทำให้ทุกชิ้น", "มองเห็นได้"], rfidText: "เราเตรียม hardware, application logic และ integration layer สำหรับ deploy RFID และ IoT อย่างมั่นใจ ตั้งแต่การอ่าน tag ครั้งแรกจนถึง operating system ที่เชื่อมต่อกัน",
    stack: [["01", "TAG", "รหัสเฉพาะและข้อมูลสินค้า"], ["02", "READER", "การรับสัญญาณที่เชื่อถือได้"], ["03", "ANTENNA", "สะพานเชื่อมการสื่อสาร"], ["04", "SOFTWARE", "ข้อมูล workflow และ integration"]],
    techLabel: "CORE TECHNOLOGY", techTitle: "เลือกความถี่ให้เหมาะกับการตัดสินใจ", tech: [["LF", "125–134 kHz", "การระบุระยะใกล้", "ระบุสัตว์ · ควบคุมการเข้าออก"], ["HF / NFC", "13.56 MHz", "ประสบการณ์แบบแตะแล้วเชื่อมต่อ", "Smart card · ชำระเงิน · ตรวจสอบของแท้"], ["UHF", "860–960 MHz", "มองเห็น inventory ระยะไกล", "Logistics · Production · ติดตามสินทรัพย์"]],
    projectsLabel: "จุดที่สร้างคุณค่า", projectsTitle: ["เชื่อมข้อมูล", "เข้ากับการทำงาน"], projects: [["PRODUCT TRACEABILITY", "ติดตามสินค้าตั้งแต่การผลิตจนถึงการกระจาย พร้อมสถานะและประวัติที่ตรวจสอบได้"], ["INVENTORY CONTROL", "ค้นหา นับ และเคลื่อนย้าย stock โดยใช้แรงงาน manual และความไม่แน่นอนน้อยลง"], ["SUPPLIER QUEUE", "บริหาร supplier, ตารางนัดหมาย และการรับสินค้าไว้ใน operational view เดียว"], ["AUTHENTICITY & NFC", "สร้างตัวตนให้สินค้าและประสบการณ์ที่น่าเชื่อถือให้ลูกค้า"], ["PRODUCTION VISIBILITY", "รวม check sheet, approval step และ dashboard ให้อยู่ใน flow เดียว"], ["CONNECTED DEVICES", "ต่อยอดระบบสู่ dispensing, access, patient หรือ event experience"]],
    ctaLabel: "พร้อมเชื่อมทุกจุดให้เห็นภาพหรือยัง?", ctaTitle: ["เริ่มจาก", "คำถามหน้างานจริง"], ctaText: "บอกเราได้ว่าปัญหา visibility, capacity หรือ quality กำลังขวางการทำงานตรงไหน เราจะช่วยวาง next step ที่ทำได้จริง", ctaAction: "พูดคุยกับ INTEVIA", footer: "RFID และระบบอุตสาหกรรมสำหรับองค์กรที่พร้อมขับเคลื่อนอย่างมีเป้าหมาย"
  }
} as const;

const headingStyle = (language: Language) => ({ fontFamily: language === "th" ? '"Noto Sans Thai", "Manrope", sans-serif' : 'Manrope, "Noto Sans Thai", sans-serif' });
function Lines({ lines }: { lines: readonly string[] }) { return <>{lines.map((line, i) => <span key={line}>{line}{i < lines.length - 1 && <br />}</span>)}</>; }
function BrandMark() { return <span className="brand-mark" aria-label="INTEVIA"><img src="/manus-storage/intevia-iv-mark_c17c09be.png" alt="" aria-hidden="true" /><span>INTE</span><b>V</b><span>IA</span></span>; }

export default function RfidServices() {
  const [language, setLanguage] = useState<Language>("en");
  const t = copy[language];
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  return <div className={`rfid-page lang-${language}`}>
    <header className="rfid-header"><a className="rfid-back" href="/"><ChevronLeft size={16} /> {t.back}</a><BrandMark /><div className="header-actions"><a className="rfid-header-contact" href="#rfid-contact">{t.contact} <ArrowRight size={15} /></a><div className="language-toggle" role="group" aria-label="Language selector"><button className={language === "en" ? "is-active" : ""} onClick={() => setLanguage("en")} aria-pressed={language === "en"}>EN</button><span>/</span><button className={language === "th" ? "is-active" : ""} onClick={() => setLanguage("th")} aria-pressed={language === "th"}>ไทย</button></div></div></header>
    <main>
      <section className="rfid-hero"><div className="rfid-hero__grid" /><div className="rfid-hero__copy"><p className="eyebrow eyebrow--light"><span /> {t.heroLabel}</p><h1 style={headingStyle(language)}><Lines lines={t.heroTitle} /></h1><p>{t.heroText}</p><a className="text-link text-link--light" href="#capabilities">{t.heroAction} <ArrowRight size={17} /></a></div><div className="rfid-hero__art" aria-hidden="true"><div className="rfid-orbit rfid-orbit--one" /><div className="rfid-orbit rfid-orbit--two" /><div className="rfid-chip"><span>RF</span><b>ID</b></div><div className="rfid-signal">· · · · ·</div></div><span className="rfid-hero__index">RFID / 01</span></section>
      <section className="rfid-intro"><p className="eyebrow"><span /> {t.introLabel}</p><div className="rfid-intro__grid"><h2 style={headingStyle(language)}><Lines lines={t.introTitle} /></h2><p>{t.introText}</p></div></section>
      <section className="rfid-capabilities" id="capabilities"><div className="rfid-section-head"><p className="eyebrow"><span /> ENGINEERING & OPERATIONS</p><h2 style={headingStyle(language)}>Four ways to<br />move the system forward</h2></div><div className="rfid-service-grid">{t.services.map(([number, title, headline, text]) => <article className="rfid-service-card" key={number}><span className="rfid-service-card__number">{number}</span><p>{title}</p><h3 style={headingStyle(language)}>{headline}</h3><span className="rfid-service-card__line" /><div>{text}</div><ArrowUpRight className="rfid-service-card__arrow" size={20} /></article>)}</div></section>
      <section className="rfid-system"><div className="rfid-system__copy"><p className="eyebrow eyebrow--light"><span /> {t.rfidLabel}</p><h2 style={headingStyle(language)}><Lines lines={t.rfidTitle} /></h2><p>{t.rfidText}</p><figure className="rfid-system__photo"><img src="/manus-storage/intevia-rfid-traceability_1a2f139a.jpg" alt={language === "en" ? "UHF RFID label being applied to a product carton on a factory conveyor" : "การติด RFID UHF บนกล่องสินค้าในสายพานการผลิต"} /><figcaption>{language === "en" ? "Traceability, made visible at the point of work." : "ทำให้ traceability มองเห็นได้ ณ จุดปฏิบัติงาน"}</figcaption></figure></div><div className="rfid-stack">{t.stack.map(([number, title, detail], i) => <div className="rfid-stack__item" key={number}><b>{number}</b><span className={`rfid-stack__icon rfid-stack__icon--${i + 1}`} /> <div><strong>{title}</strong><small>{detail}</small></div></div>)}</div></section>
      <section className="rfid-technology"><div className="rfid-section-head"><p className="eyebrow"><span /> {t.techLabel}</p><h2 style={headingStyle(language)}>{t.techTitle}</h2></div><div className="rfid-tech-grid">{t.tech.map(([band, freq, range, use]) => <article key={band}><span>{band}</span><strong>{freq}</strong><h3 style={headingStyle(language)}>{range}</h3><p>{use}</p></article>)}</div></section>
      <section className="rfid-projects"><div className="rfid-section-head"><p className="eyebrow"><span /> {t.projectsLabel}</p><h2 style={headingStyle(language)}><Lines lines={t.projectsTitle} /></h2></div><div className="rfid-project-grid">{t.projects.map(([title, text], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p><ArrowRight size={16} /></article>)}</div></section>
      <section className="rfid-cta" id="rfid-contact"><div className="rfid-cta__mark">IV</div><div><p className="eyebrow eyebrow--light"><span /> {t.ctaLabel}</p><h2 style={headingStyle(language)}><Lines lines={t.ctaTitle} /></h2><p>{t.ctaText}</p><a className="diagnostic-button" href={`mailto:admin@intevia.co.th?subject=${encodeURIComponent(language === "en" ? "RFID and Industrial Systems" : "RFID และระบบอุตสาหกรรม")}`}>{t.ctaAction} <ArrowRight size={17} /></a></div></section>
    </main>
    <footer className="site-footer rfid-footer"><div className="site-footer__brand"><BrandMark /><p>Intelligence · Strategy · Action</p><p className="site-footer__statement">{t.footer}</p></div><div className="site-footer__links"><div><p className="footer-label">NAVIGATE</p><a href="/">{t.back}</a><a href="#capabilities">{t.nav}</a></div><div><p className="footer-label">CONTACT</p><a href="mailto:admin@intevia.co.th">admin@intevia.co.th</a><a href="https://www.intevia.co.th" target="_blank" rel="noreferrer">www.intevia.co.th</a></div></div><div className="site-footer__bottom"><span>© {new Date().getFullYear()} INTEVIA</span><span>RFID · IOT · INDUSTRIAL SYSTEMS</span></div></footer>
  </div>;
}
